import { PersonListItem } from '../../types/frontend.types';

// Mock list data to ensure grid displays properly while API is connecting
export function getMockListData(): PersonListItem[] {
  return [
    {
      id: "person-001",
      name: "Michael Chen",
      jobTitle: "Senior Software Engineer",
      avatarInitials: "MC",
      avatarBg: "#ff6b6b",
      avatarUrl: undefined,
      department: "Engineering",
      currentLocation: "Barcelona, Spain",
      permanentHome: "San Francisco, CA",
      status: { label: "Active", color: "#22c55e" },
      email: "michael.chen@company.com",
      personalEmail: "m.chen@gmail.com",
      phone: "+1 555-0123"
    },
    {
      id: "person-002", 
      name: "Sarah Johnson",
      jobTitle: "Product Manager",
      avatarInitials: "SJ",
      avatarBg: "#4ecdc4",
      avatarUrl: undefined,
      department: "Product",
      currentLocation: "London, UK",
      permanentHome: "New York, NY",
      status: { label: "On Assignment", color: "#3b82f6" },
      email: "sarah.johnson@company.com",
      personalEmail: "sarahj@hotmail.com",
      phone: "+44 20 7123 4567"
    },
    {
      id: "person-003",
      name: "David Rodriguez",
      jobTitle: "UX Designer", 
      avatarInitials: "DR",
      avatarBg: "#845ec2",
      avatarUrl: undefined,
      department: "Design",
      currentLocation: "Toronto, Canada",
      permanentHome: "Mexico City, Mexico",
      status: { label: "Remote", color: "#f59e0b" },
      email: "david.rodriguez@company.com",
      personalEmail: "d.rodriguez@yahoo.com",
      phone: "+1 416-555-0987"
    },
    {
      id: "person-004",
      name: "Emma Thompson",
      jobTitle: "Data Scientist",
      avatarInitials: "ET",
      avatarBg: "#ffa726",
      avatarUrl: undefined,
      department: "Analytics",
      currentLocation: "Amsterdam, Netherlands", 
      permanentHome: "Boston, MA",
      status: { label: "Active", color: "#22c55e" },
      email: "emma.thompson@company.com",
      personalEmail: "emma.t@outlook.com",
      phone: "+31 20 123 4567"
    },
    {
      id: "person-005",
      name: "Alex Kim",
      jobTitle: "DevOps Engineer",
      avatarInitials: "AK", 
      avatarBg: "#26a69a",
      avatarUrl: undefined,
      department: "Infrastructure",
      currentLocation: "Seoul, South Korea",
      permanentHome: "Los Angeles, CA",
      status: { label: "On Leave", color: "#ef4444" },
      email: "alex.kim@company.com",
      personalEmail: "alexkim@gmail.com",
      phone: "+82 2 1234 5678"
    },
    {
      id: "person-006",
      name: "Maria Santos",
      jobTitle: "Marketing Manager",
      avatarInitials: "MS",
      avatarBg: "#ec407a",
      avatarUrl: undefined,
      department: "Marketing",
      currentLocation: "Madrid, Spain",
      permanentHome: "Miami, FL",
      status: { label: "Active", color: "#22c55e" },
      email: "maria.santos@company.com",
      personalEmail: "m.santos@gmail.com",
      phone: "+34 91 123 4567"
    },
    {
      id: "person-007",
      name: "James Wilson",
      jobTitle: "Sales Director",
      avatarInitials: "JW",
      avatarBg: "#42a5f5",
      avatarUrl: undefined,
      department: "Sales",
      currentLocation: "Singapore",
      permanentHome: "Chicago, IL",
      status: { label: "Traveling", color: "#9333ea" },
      email: "james.wilson@company.com",
      personalEmail: "jwilson@outlook.com",
      phone: "+65 6123 4567"
    },
    {
      id: "person-008",
      name: "Lisa Anderson",
      jobTitle: "HR Business Partner",
      avatarInitials: "LA",
      avatarBg: "#66bb6a",
      avatarUrl: undefined,
      department: "Human Resources",
      currentLocation: "Sydney, Australia",
      permanentHome: "Portland, OR",
      status: { label: "Active", color: "#22c55e" },
      email: "lisa.anderson@company.com",
      personalEmail: "l.anderson@yahoo.com",
      phone: "+61 2 1234 5678"
    },
    {
      id: "person-009",
      name: "Robert Brown",
      jobTitle: "Finance Manager",
      avatarInitials: "RB",
      avatarBg: "#ff7043",
      avatarUrl: undefined,
      department: "Finance",
      currentLocation: "Dublin, Ireland",
      permanentHome: "Dallas, TX",
      status: { label: "Active", color: "#22c55e" },
      email: "robert.brown@company.com", 
      personalEmail: "rbrown@gmail.com",
      phone: "+353 1 123 4567"
    },
    {
      id: "person-010",
      name: "Jennifer Lee",
      jobTitle: "Operations Manager",
      avatarInitials: "JL",
      avatarBg: "#ab47bc",
      avatarUrl: undefined,
      department: "Operations",
      currentLocation: "Tokyo, Japan",
      permanentHome: "Seattle, WA",
      status: { label: "On Assignment", color: "#3b82f6" },
      email: "jennifer.lee@company.com",
      personalEmail: "jennifer.lee@hotmail.com",
      phone: "+81 3 1234 5678"
    }
  ];
}